# Site settings
title: CSNE
subtitle: 
email: macaquenet@gmail.com
description: 
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://comparative-social-network-ecology.github.io/" # the base hostname & protocol for your site
author: CSNE
lang: en_US

# Social settings
github_url: 
slack_url: 

# Build settings
markdown: kramdown

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Disables sidebar for now
defaults:
  - scope:
      path: ""
    values:
      layout: single
      sidebar: false

